- name: Deploy K8s arch
  hosts: hypervisor
  vars:
    ansible_python_interpreter: '/usr/bin/python'
  remote_user: proxmoxadmin

  tasks:
  - name: Create nodes for K8s cluster
    debug:
      msg: "'{{ lookup('env', 'HOME') }}' is the HOME environment variable."
      msg: "{{ lookup('pipe', 'hostname') }}"
  - name: Create new container for K8s master
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      node: Proxmox-VE
      #pubkey: '~/.ssh/id_rsa.pub'
      vmid : 500
      hostname: 'k8smaster'
      ostemplate: 'local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz'
      password: 123456
      pubkey: "{{ lookup('pipe', 'cat ~/.ssh/id_rsa.pub') }}"
      cores: 2
      cpus: 1
      memory: 1024
      description: 'container for kubernetes master'
      disk: '8'
      netif: '{"net0":"name=eth0,gw=192.168.0.254,ip=192.168.0.100/24,bridge=vmbr1"}'
      storage: 'data'
      unprivileged: yes
  - name: Start master
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      vmid : 500
      state: 'started'
  - name: Create new container for K8s worker1
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      node: Proxmox-VE
      #pubkey: '~/.ssh/id_rsa.pub'
      vmid : 501
      hostname: 'k8sworker1'
      ostemplate: 'local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz'
      password: 123456
      pubkey: "{{ lookup('pipe', 'cat ~/.ssh/id_rsa.pub') }}"
      cores: 2
      cpus: 1
      memory: 1024
      description: 'container for kubernetes master'
      disk: '8'
      netif: '{"net0":"name=eth0,gw=192.168.0.254,ip=192.168.0.101/24,bridge=vmbr1"}'
      storage: 'data'
      unprivileged: yes
  - name: Start worker1
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      vmid : 501
      state: 'started'
  - name: Create new container for K8s worker2
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      node: Proxmox-VE
      #pubkey: '~/.ssh/id_rsa.pub'
      vmid : 502
      hostname: 'k8sworker2'
      ostemplate: 'local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz'
      password: 123456
      pubkey: "{{ lookup('pipe', 'cat ~/.ssh/id_rsa.pub') }}"
      cores: 2
      cpus: 1
      memory: 1024
      description: 'container for kubernetes worker2'
      disk: '8'
      netif: '{"net0":"name=eth0,gw=192.168.0.254,ip=192.168.0.102/24,bridge=vmbr1"}'
      storage: 'data'
      unprivileged: yes
  - name: Start worker2
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      vmid : 502
      state: 'started'
  - name: Create new container for K8s data
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      node: Proxmox-VE
      #pubkey: '~/.ssh/id_rsa.pub'
      vmid : 503
      hostname: 'k8sdata'
      ostemplate: 'local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz'
      password: 123456
      pubkey: "{{ lookup('pipe', 'cat ~/.ssh/id_rsa.pub') }}"
      cores: 2
      cpus: 1
      memory: 1024
      description: 'container for kubernetes master'
      disk: '8'
      netif: '{"net0":"name=eth0,gw=192.168.0.254,ip=192.168.0.103/24,bridge=vmbr1"}'
      storage: 'data'
      unprivileged: yes
  - name: Start data
    community.general.proxmox:
      api_user: 'proxmoxadmin@pam'
      api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
      api_host: localhost
      vmid : 503
      state: 'started'
